SELECT DEPT_NAME AS Department, NAME as Employee, Salary FROM
(SELECT D.NAME AS DEPT_NAME, E.NAME, E.SALARY, 
DENSE_RANK() OVER(PARTITION BY D.NAME ORDER BY E.SALARY DESC) AS RK FROM 
DEPARTMENT AS D JOIN EMPLOYEE AS E ON D.ID = E.DEPARTMENTID
) AS SUB
WHERE RK <= 3
ORDER BY DEPT_NAME