WITH CTE AS (
    SELECT H.HACKER_ID, H.NAME, COUNT(*) AS CNT
    FROM CHALLENGES AS C JOIN HACKERS AS H USING(HACKER_ID)
    GROUP BY H.HACKER_ID, H.NAME
)

SELECT CTE.HACKER_ID, CTE.NAME, CTE.CNT
FROM CTE
WHERE CNT = (SELECT MAX(CNT) FROM CTE)
OR CNT IN (
    SELECT CNT FROM CTE 
    GROUP BY CNT
    HAVING COUNT(*) = 1
)
ORDER BY CTE.CNT DESC, CTE.HACKER_ID;