SELECT H.HACKER_ID, H.NAME,
SUM(SUB.MAX_SCORE) AS TOTAL_SCORE
FROM HACKERS AS H
JOIN (
    SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS MAX_SCORE
    FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID
) AS SUB
ON H.HACKER_ID = SUB.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING TOTAL_SCORE > 0
ORDER BY 3 DESC, 1 ASC;