SELECT CART_ID FROM CART_PRODUCTS
WHERE NAME = 'Yogurt'

INTERSECT

SELECT CART_ID FROM CART_PRODUCTS
WHERE NAME = 'Milk'

ORDER BY CART_ID

--------------------------------

SELECT CART_ID FROM CART_PRODUCTS
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) >= 2
ORDER BY CART_ID