SELECT A.HISTORY_ID,
(TIMESTAMPDIFF(DAY,A.START_DATE,A.END_DATE)+1) * 
(B.DAILY_FEE - (B.DAILY_FEE / 100*REPLACE(IFNULL(C.DISCOUNT_RATE,0),'%',''))) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
JOIN CAR_RENTAL_COMPANY_CAR AS B ON A.CAR_ID = B.CAR_ID AND B.CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON B.CAR_TYPE = C.CAR_TYPE
AND C.DURATION_TYPE = CASE WHEN (TIMESTAMPDIFF(DAY,A.START_DATE,A.END_DATE)+1) >=90 THEN '90일 이상'
                                  WHEN (TIMESTAMPDIFF(DAY,A.START_DATE,A.END_DATE)+1) >=30 THEN '30일 이상'
                                  WHEN (TIMESTAMPDIFF(DAY,A.START_DATE,A.END_DATE)+1) >=7 THEN '7일 이상'
                                  ELSE '' END
ORDER BY FEE DESC,A.HISTORY_ID DESC