SELECT 
    A.CAR_ID, 
    A.CAR_TYPE, 
    ROUND(A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE / 100), 0) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS A 
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C 
    ON A.CAR_TYPE = C.CAR_TYPE 
    AND C.DURATION_TYPE = '30일 이상'
WHERE 
    (A.CAR_TYPE = 'SUV' OR A.CAR_TYPE = '세단')
    AND A.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND ROUND(A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE / 100), 0) BETWEEN 500000 AND 1999999
ORDER BY 
    FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;
